.TH "Bille" 3 "Fri Dec 4 2015" "Version 1.0" "Pacman" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Bille \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBBonus\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBille\fP (float x, float y, bool power, int score)"
.br
.RI "\fI\fBBille::Bille\fP Constructeur avec paramètre d'une croquette\&. \fP"
.ti -1c
.RI "float \fBgetx\fP ()"
.br
.RI "\fI\fBBille::getx\fP retourne position horizontale de la croquette\&. \fP"
.ti -1c
.RI "float \fBgety\fP ()"
.br
.RI "\fI\fBBille::gety\fP retourne la position verticale de la croquette\&. \fP"
.ti -1c
.RI "bool \fBgetpower\fP ()"
.br
.RI "\fI\fBBille::getpower\fP retourne l'état de la croquette\&. \fP"
.ti -1c
.RI "void \fBsetx\fP (float x)"
.br
.RI "\fI\fBBille::setx\fP modifie la position à l'horizontale de la croquette\&. \fP"
.ti -1c
.RI "void \fBsety\fP (float y)"
.br
.RI "\fI\fBBille::sety\fP modifie la position à la verticale de la croquette\&. \fP"
.in -1c
.SS "Additional Inherited Members"
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Bille::Bille (float x, float y, bool power, int score)"

.PP
\fBBille::Bille\fP Constructeur avec paramètre d'une croquette\&. 
.PP
\fBParameters:\fP
.RS 4
\fIx\fP Position horizontale de la croquette 
.br
\fIy\fP Position verticale de la croquette 
.br
\fIpower\fP état de la croquette 
.br
\fIscore\fP 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "bool Bille::getpower ()"

.PP
\fBBille::getpower\fP retourne l'état de la croquette\&. 
.PP
\fBReturns:\fP
.RS 4
état de la croquette 
.RE
.PP

.SS "float Bille::getx ()"

.PP
\fBBille::getx\fP retourne position horizontale de la croquette\&. 
.PP
\fBReturns:\fP
.RS 4
position horizontale 
.RE
.PP

.SS "float Bille::gety ()"

.PP
\fBBille::gety\fP retourne la position verticale de la croquette\&. 
.PP
\fBReturns:\fP
.RS 4
position verticale 
.RE
.PP

.SS "void Bille::setx (float x)"

.PP
\fBBille::setx\fP modifie la position à l'horizontale de la croquette\&. 
.PP
\fBParameters:\fP
.RS 4
\fIx\fP nouvelle position 
.RE
.PP

.SS "void Bille::sety (float y)"

.PP
\fBBille::sety\fP modifie la position à la verticale de la croquette\&. 
.PP
\fBParameters:\fP
.RS 4
\fIy\fP nouvelle position à la verticale 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Pacman from the source code\&.
