.TH "C:/Users/kelku/Documents/GitHub/pac/Pacman/Graphics Directory Reference" 3 "Fri Dec 4 2015" "Version 1.0" "Pacman" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/kelku/Documents/GitHub/pac/Pacman/Graphics Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBaffichage\&.cpp\fP"
.br
.ti -1c
.RI "file \fBaffichage\&.h\fP"
.br
.in -1c
