.TH "Fruit" 3 "Fri Dec 4 2015" "Version 1.0" "Pacman" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Fruit \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBBonus\fP\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBname\fP { \fBcherry\fP, \fBstrawberry\fP, \fBorange\fP, \fBapple\fP, \fBgrapes\fP, \fBgalaxian\fP, \fBbell\fP, \fBkey\fP }"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFruit\fP (float x, float y, name n, int score)"
.br
.RI "\fIFruit::Fruit constructeur de fruit avec 4 paramètres\&. \fP"
.in -1c
.SS "Additional Inherited Members"
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Fruit::Fruit (float x, float y, name n, int score)"

.PP
Fruit::Fruit constructeur de fruit avec 4 paramètres\&. 
.PP
\fBParameters:\fP
.RS 4
\fIx\fP position horizontale 
.br
\fIy\fP position verticale 
.br
\fIn\fP nom du fruit 
.br
\fIscore\fP 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Pacman from the source code\&.
