.TH "Labyrinthe" 3 "Fri Dec 4 2015" "Version 1.0" "Pacman" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Labyrinthe \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBLabyrinthe\fP (float, float, int, int)"
.br
.RI "\fI\fBLabyrinthe::Labyrinthe\fP constructeur avec 4 paramètre du labyrinthe\&. \fP"
.ti -1c
.RI "int \fBgetX\fP ()"
.br
.RI "\fI\fBLabyrinthe::getX\fP retourne la position horizontale\&. \fP"
.ti -1c
.RI "int \fBgetY\fP ()"
.br
.RI "\fI\fBLabyrinthe::getY\fP retourne la position verticale\&. \fP"
.ti -1c
.RI "int \fBgetW\fP ()"
.br
.RI "\fI\fBLabyrinthe::getW\fP retourne la largeur du labyrinthe\&. \fP"
.ti -1c
.RI "int \fBgetH\fP ()"
.br
.RI "\fI\fBLabyrinthe::getH\fP retourne la hauteur du \fBLabyrinthe\fP\&. \fP"
.ti -1c
.RI "QGraphicsPixmapItem * \fBgetgobj\fP ()"
.br
.RI "\fI\fBLabyrinthe::getgobj\fP retourne le labyrinthe\&. \fP"
.ti -1c
.RI "\fBLabyrinthe\fP * \fBresize\fP (int w, int h)"
.br
.RI "\fI\fBLabyrinthe::resize\fP adapte la taille du labyrinthe\&. \fP"
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Labyrinthe::Labyrinthe (float x, float y, int width, int height)"

.PP
\fBLabyrinthe::Labyrinthe\fP constructeur avec 4 paramètre du labyrinthe\&. 
.PP
\fBParameters:\fP
.RS 4
\fIx\fP position horizontale 
.br
\fIy\fP position verticale 
.br
\fIwidth\fP largeur 
.br
\fIheight\fP hauteur 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "QGraphicsPixmapItem * Labyrinthe::getgobj ()"

.PP
\fBLabyrinthe::getgobj\fP retourne le labyrinthe\&. 
.PP
\fBReturns:\fP
.RS 4
labyrinthe 
.RE
.PP

.SS "int Labyrinthe::getH ()"

.PP
\fBLabyrinthe::getH\fP retourne la hauteur du \fBLabyrinthe\fP\&. 
.PP
\fBReturns:\fP
.RS 4
hauteur 
.RE
.PP

.SS "int Labyrinthe::getW ()"

.PP
\fBLabyrinthe::getW\fP retourne la largeur du labyrinthe\&. 
.PP
\fBReturns:\fP
.RS 4
largeur 
.RE
.PP

.SS "int Labyrinthe::getX ()"

.PP
\fBLabyrinthe::getX\fP retourne la position horizontale\&. 
.PP
\fBReturns:\fP
.RS 4
position horizontale 
.RE
.PP

.SS "int Labyrinthe::getY ()"

.PP
\fBLabyrinthe::getY\fP retourne la position verticale\&. 
.PP
\fBReturns:\fP
.RS 4
position verticale 
.RE
.PP

.SS "\fBLabyrinthe\fP * Labyrinthe::resize (int w, int h)"

.PP
\fBLabyrinthe::resize\fP adapte la taille du labyrinthe\&. 
.PP
\fBParameters:\fP
.RS 4
\fIw\fP largeur 
.br
\fIh\fP hauteur 
.RE
.PP
\fBReturns:\fP
.RS 4
Le labyrinthe mis à la bonne taille 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Pacman from the source code\&.
