.TH "Porte" 3 "Fri Dec 4 2015" "Version 1.0" "Pacman" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Porte \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPorte\fP (float x, float y)"
.br
.ti -1c
.RI "QGraphicsPixmapItem * \fBgetgobj\fP ()"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Pacman from the source code\&.
